---
title: "2022.10.04_R_class_Practice3_2"
author: "Berrica"
date: "2022-10-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Practice3.2 in R class


## The first element
```{r, eval = T}
first <- data.frame(before_diet = c(104, 95, 87, 77, 112), 
                    after_diet = c(104, 95, 87, 77, 112))
mode(first)
str(first)
```

## The second element
```{r, eval = T}

second <- data.frame(subject = c(row.names(first)), 
                     weight_loss = (first$before_diet - first$after_diet)/100)
mode(second)
str(second)
```

## The third element: How much I enjoy manipulating data in R!!!
```{r, eval = T, echo = F}
# install.packages("ggplot2")
# install.packages("pryr")
library(dplyr)
library(ggplot2)
library(pryr)

# heart curve formula
heart <- quote((x^2 + y^2 - 1)^3 - x^2 * y^3)

# formula for heart curve at a given x
heart_at_x <- function(x) {
  function(y) eval(substitute_q(heart, list(x = x)), list(y = y))
}

# trace the heart curve
# by evaluating the heart curve formula at each x, then finding the roots of the
# resulting formula in y; e.g. a x==0, find the roots of (y^2 - 1)^3 = 0
# broken up into upper and lower parts (h_y1 and h_y2)
heart_x <- seq(-1.136, 1.136, 0.001)
heart_y_lower <- sapply(heart_x, function(x) uniroot(heart_at_x(x), c(-2, 0.6))$root)
heart_y_upper <- sapply(heart_x, function(x) uniroot(heart_at_x(x), c(0.6, 2))$root)

# put together data frame
heart_df <- data.frame(x = rep(heart_x, 2), 
                       y = c(heart_y_lower, heart_y_upper))

# show outline
#with(heart_df, plot(x, y))

# create a data frame with one row per x, so we can fill in the heart
heart_df_minmax <- data.frame(x = heart_x,  
                              y_min = heart_y_lower, 
                              y_max = heart_y_upper)

set.seed(20150214)

# fill in the heart by generating random deviates at each x 
# and rejecting those that fall outside the heart curve
heart_full <- apply(heart_df_minmax, 
                    1, 
                    function(w) {
                      x <- w["x"]
                      y_min = w["y_min"]
                      y_max = w["y_max"]
                      y <- rnorm(2, mean = 0.33)
                      y <- y[between(y, y_min, y_max)]
                      x <- x[any(is.finite(y))]
                      data.frame(x, y, row.names = NULL)
                    })

# change from list to data frame
heart_full <- bind_rows(heart_full)

# add random numbers for color and size
heart_full <- heart_full %>% 
  mutate(z1 = runif(n()), 
         z2 = pmin(abs(rnorm(n())), 3), 
         order = runif(n())) %>%
  arrange(order)


# plot the heart
p <- ggplot(heart_full, 
            aes(x, y, color = z1, size = z2)) + 
  geom_point(pch = -1 * as.hexmode(9829)) + 
  scale_color_gradient(limits = c(0, 1), low = "red3", high = "pink") + 
  scale_size(limits = c(0, 3), range = c(0.1, 20)) + 
  theme_bw() +
  theme(legend.position="none", 
        axis.title.x=element_blank(),
        axis.text.x=element_blank(), 
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(), 
        axis.ticks.y=element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank())+
  scale_y_continuous(breaks = NULL) +
  scale_x_continuous(breaks = NULL)
p
```

## Outcome
```{r, eval = T}
#Make a list called BUBBLE_DIET
BUBBLE_DIET <- list(first, WEIGHT_LOSS = second, ILOVER = p)
mode(BUBBLE_DIET)
str(BUBBLE_DIET)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
